# docker-compose.yml
version: '3'
services:
  analytics_sc:
    build:
      context: .
    container_name: analytics_sc
    ports:
      - "8506:8506"
    depends_on:
      - db
      # - redis

  db:
    image: postgis/postgis:13-3.1
    container_name: streamlit_postgis
    environment:
      POSTGRES_DB: sitcenter_postgis_datalake
      POSTGRES_USER: la_noche_estrellada
      POSTGRES_PASSWORD: Cfq,thNb13@
    ports:
      - "6592:5439"